 # Jason Ye - yeja@oregonstate.edu
 # Corey Hemphill - hemphilc@oregonstate.edu
 # CS444 - Fragmentation Test Makefile
 # November 26, 2017
 # Makefile
 #
 # #************************************************************************
 # # Reference: makefile from Materials from Class by Dr. Kevin McGrath
 # #************************************************************************

all: frag_test

frag_test: frag_test.c
	gcc -std=c99 frag_test.c -o frag_test
 
clean:
	rm frag_test
