 # Jason Ye - yeja@oregonstate.edu
 # Corey Hemphill - hemphilc@oregonstate.edu
 # CS444 - Concurrency 1 Makefile
 # October 9, 2017
 # Makefile

#************************************************************************
# Reference: makefile from Materials from Class by Dr. Kevin McGrath
#************************************************************************

all: concurrency

concurrency2: concurrency.c 
	gcc -std=c99 concurrency.c -o concurrency -lpthread

clean:
	rm concurrency
