 # Jason Ye - yeja@oregonstate.edu
 # Corey Hemphill - hemphilc@oregonstate.edu
 # CS444 - Concurrency 2 Report Makefile
 # October 26, 2017
 # Makefile

#************************************************************************
# Reference: makefile from Materials from Class by Dr. Kevin McGrath
#************************************************************************

all: concurrency2

concurrency2: concurrency2.c 
	gcc concurrency2.c -o concurrency2 -std=c99 -g lpthread

clean:
	rm concurrency2